### ISSUE TITLE
"Sudo" token is no longer supported by Gitlab, migration impossible.

### ISSUE THREAD

**Issue by romanr** [redmine-gitlab-migrator/redmine-gitlab-migrator#26] opened 2018-02-22 00:27 UTC
This is similar to #17 but more fatal. The Gitlab token generation no longer have "sudo" option, and previous "private key" is no longer available. So any key you generate will not work.

Current Gitlab and current script version from repo:

```
INFO: create issue "..... " failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 396, in main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 278, in perform_migrate_issues
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/gitlab.py", line 155, in create_issue
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/__init__.py", line 46, in post
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/__init__.py", line 37, in _req
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gitlab.com/api/v3/projects/432321/issues
```

Milestones were created correctly with the same token parameter. But issues can not be created.

**Comment by lambdaupb** [comment] 2018-03-02 11:45
I had this issue, but it was caused by the users the admin is trying to impersonate not having the rights to access the repo. You need to add the users to the repo before migrating issues.

**Comment by romanr** [comment] 2018-05-29 10:28
Added users and user mapping file, still having the same error.
Looks like redmine-gitlab-migrator is now only for those who have their own self-hosted gitlab.

**Comment by marcofaber** [comment] 2018-08-08 18:56
Does anyone know a workaround for this problem? I got the same error with a GitLab 11.0.2 that is not under my control. I tried the current version of the fork of @johan-smits, but I got the same error.

**Comment by scambra** [comment] 2018-08-09 07:27
I added --no-sudo to allow migrating to gitlab.com or any other gitlab instance where admin access is not allowed. I forgot to add this optiont to readme.

https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator/commit/e67aa99084a01e61e485942e5794f49a9403a423

I could migrate issues to gitlab.com by end of May or beginning of June with this option, although issue creator is lost.

**Comment by scambra** [comment] 2018-08-09 07:30
fixed in https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator/commit/e67aa99084a01e61e485942e5794f49a9403a423 and added doc in b991142

**Closed by scambra** 2018-08-09 07:30 UTC

**Comment by marcofaber** [comment] 2018-08-09 14:27
Thanks a lot! It works for me. I just had to change the line

https://github.com/johan-smits/redmine-gitlab-migrator/blob/32851bb2722e7c1b3dfcc25e69b00d67c25a9feb/redmine_gitlab_migrator/gitlab.py#L10

from
```python
from json.decoder import JSONDecodeError
```
to
```python
from simplejson.decoder import JSONDecodeError
```
I found this solution somewhere yesterday. But I also have an old Debian Jessie with Python 3.4.2.
